In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
 #scalar
 scalar = torch.tensor(7)
 scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
print(scalar)

tensor(7)


In [5]:
vector= torch.tensor([7,7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
MATRIX= torch.tensor([[7,8],[9,10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
Tensor= torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])

In [12]:
Tensor.ndim

3

In [13]:
Tensor.shape

torch.Size([1, 3, 3])

In [14]:
Tensor[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

**Random Tensors**
the way many nn start with random weight i.e ranodm num then adjust

In [15]:
 random_tensor=torch.rand(4,3)
 random_tensor

tensor([[0.2596, 0.3036, 0.5180],
        [0.9771, 0.9634, 0.2758],
        [0.0803, 0.3424, 0.9016],
        [0.8320, 0.2105, 0.7250]])

In [16]:
random_tensor.ndim

2

In [17]:
random_tensor.shape

torch.Size([4, 3])

In [18]:
Random_image_tensor=torch.rand(size=(3,224,224))# height , width , color channels

In [19]:
Random_image_tensor.shape,Random_image_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [20]:
 zeros=torch.zeros(size=(4,3))
 zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [21]:
zeros*random_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [22]:
ones=torch.ones(size=(4,3))
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [23]:
ones.dtype

torch.float32

**Creating Range pf tensors**

In [24]:
tensor_range=torch.arange(start=0,end=1000,step=66)
tensor_range

tensor([  0,  66, 132, 198, 264, 330, 396, 462, 528, 594, 660, 726, 792, 858,
        924, 990])

In [25]:
 ten_zeros=torch.ones_like(input=tensor_range)
 ten_zeros

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [26]:
tensor_range.shape,ten_zeros.shape

(torch.Size([16]), torch.Size([16]))

**Tesnor** **DataTypes**
Tensors data types is one odf nig 3 errors you'll run into with Pytorch & deep learning:
1. Tensors not right data type
2. Tensors not right shape
3.Tenosr not on the right device read ***precision in computing***

In [27]:
float_32_tensor=torch.tensor([3.0,5.0,6.0], dtype=torch.float32 #what data type
                             ,device="cpu" # what device
                             ,requires_grad=False)# wheather or not to track gradients

In [28]:
 float_32_tensor.dtype

torch.float32

In [29]:
float_16_tensor= float_32_tensor.type(torch.half)

In [30]:
float_16_tensor.dtype

torch.float16

In [31]:
float_16_tensor*float_32_tensor

tensor([ 9., 25., 36.])

In [34]:
int_32_tensor=torch.tensor([3,4,5],dtype=torch.int64)

In [35]:
int_32_tensor*float_32_tensor

tensor([ 9., 20., 30.])

tensor.dtype, tensro.shape, tensor.device

In [37]:
some_tensor= torch.rand(3,4)

In [38]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.9004, 0.9380, 0.6172, 0.5494],
        [0.4417, 0.5499, 0.9555, 0.7013],
        [0.3191, 0.6117, 0.7683, 0.9484]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


Manupulating tensors

operation include
*addition
*sub
*multipli
division
*Mat Mul


In [40]:
tensor=torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [41]:
#Multiply
tensor*10

tensor([10, 20, 30])

In [42]:
#sub
tensor-10

tensor([-9, -8, -7])

In [44]:
#try out pytorch in-built functions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [45]:
torch.sub(tensor,10)

tensor([-9, -8, -7])

In [54]:
tensor1=torch.rand(3,4)
tensor2=torch.rand(4,3)
print(torch.matmul(tensor1,tensor2))

tensor([[0.4252, 0.6995, 1.2965],
        [0.3461, 0.3856, 0.9162],
        [0.6323, 1.1311, 2.0009]])


In [55]:
tensor=torch.tensor([1,2,3])
print(tensor*tensor)

tensor([1, 4, 9])


In [57]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 343 µs, sys: 0 ns, total: 343 µs
Wall time: 284 µs


tensor(14)

**SHAPE** **ERRORS**

In [64]:
#shapes for mat mul
tensor_A=torch.tensor([[1,2],[3,4],[5,6]])
tensor_B=torch.tensor([[7,10],[8,11],[9,12]])

In [65]:
torch.matmul(tensor_A,tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [67]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [68]:
  torch.matmul(tensor_A,tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [70]:
tensor_B.shape,tensor_B.T.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [71]:
print(f"tensor_A:{tensor_A.shape}, tensor_B:{tensor_B.shape}")
print(f"tensor_A:{tensor_A.shape}, tensor_B.T:{tensor_B.T.shape}")
print(f"mul(tensor_A,tensor_B.T):{torch.matmul(tensor_A,tensor_B.T)}")
print(f"mul(tensor_A,tensor_B.T):{torch.matmul(tensor_A,tensor_B.T).shape}")

tensor_A:torch.Size([3, 2]), tensor_B:torch.Size([3, 2])
tensor_A:torch.Size([3, 2]), tensor_B.T:torch.Size([2, 3])
mul(tensor_A,tensor_B.T):tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
mul(tensor_A,tensor_B.T):torch.Size([3, 3])


In [85]:
 ## Finding the min max mean sum etc( tensor aggregation)
 x= torch.arange(0,100,10)
 x,x.dtype
 x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [86]:
torch.min(x),x.min()

(tensor(0), tensor(0))

In [87]:
torch.max(x),x.max()

(tensor(90), tensor(90))

In [88]:
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean() #data type issue

(tensor(45.), tensor(45.))

In [91]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

FInding the postional max and min

In [94]:
x=torch.arange(1,100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [95]:
x.argmin()

tensor(0)

In [96]:
x.argmax()

tensor(9)

In [97]:
x[9]

tensor(91)

Rshaping , stacking,  sqezing and unsqueezing tensors
REshapinh reshapes an input tensor to a dedined shape
* views- return view of an input rtenspr of certain shape but keep mem as orginal tensor


In [111]:
import torch
x=torch.arange(1,10,dtype=torch.float32)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [113]:
x_reshaped=x.reshape(1,9) #(9,1)
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [114]:
#change the view
z=x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [115]:
z[:,0]=5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [118]:
#stack the tensors
x_stacked=torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [119]:
x_reshaped, x_reshaped.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [122]:
x_reshaped.squeeze(), x_reshaped.squeeze().shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [124]:
#torch.squeeze() - remove all single dimension
print(f"previous tensor:{x_reshaped}")
print(f"previous shape:{x_reshaped.shape}")
x_squeezed=x_reshaped.squeeze()
print(f"new tensor:{x_squeezed}")
print(f"new shape:{x_squeezed.shape}")

previous tensor:tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
previous shape:torch.Size([1, 9])
new tensor:tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
new shape:torch.Size([9])


In [129]:
x_unsqueezed=x_squeezed.unsqueeze(dim=0)
print(f"new tensor:{x_unsqueezed}")
print(f"new shape:{x_unsqueezed.shape}")

new tensor:tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
new shape:torch.Size([1, 9])


In [130]:
#torch.permute
x_original=torch.rand(size=(224,224,3))
x_original.shape

torch.Size([224, 224, 3])

In [136]:
x_permuted=torch.permute(x_original,(2,0,1))
x_permuted.shape

torch.Size([3, 224, 224])

In [ ]:
## Indexing (Selecting data from tensors)

In [141]:
import torch
x= torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [142]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [146]:
x[0][1]

tensor([4, 5, 6])

In [148]:
x[0][0][1]

tensor(2)

In [149]:
#yoou cal also use : to selct all of target dimension
x[:,0]

tensor([[1, 2, 3]])

In [158]:
#Get all values of 0th and 1st demensions but only index 1 od 2nd dimension
x[:  ,:,1]

tensor([2, 5, 8])

In [154]:
x[ :, 1, :]

tensor([5])

In [159]:
print(x[0][2][2])

tensor(9)


In [161]:
print(x[:,:,2])

tensor([[3, 6, 9]])


Pytorch and numpy
Numpu is a popoular scific ptrhocn numerical computing lib
and because of thsi ptoch has functioanlity to iterach with it

In [163]:
import torch
import numpy as np

In [171]:
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)# when coverting numpy to tesor the trnosr takes nu,py float 64 as dtye of tensor
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [172]:
#chage the val of array , what will this do to tensor?
array= array+1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [178]:
tensor= torch.ones(7)
numpy_tensor= tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

#reporducability
inshort how the nn works , genrated random numbers and update -> update until less loss
 to reduce the random numbers in nn and pytorjc comes the concep of **random seed**

 Essentially what the random seed does is "flavour" the randomness


In [180]:
#Reproducability (trying to take random out of random)

import torch

random_tenosr_A = torch.rand(3,4)
random_tenosr_B = torch.rand(3,4)
print(random_tenosr_A)
print(random_tenosr_B)
print(random_tenosr_A == random_tenosr_B)

tensor([[0.5054, 0.0774, 0.8463, 0.8229],
        [0.5015, 0.5073, 0.0495, 0.2595],
        [0.2974, 0.7442, 0.5303, 0.7336]])
tensor([[0.4279, 0.3744, 0.6675, 0.7168],
        [0.0630, 0.9957, 0.0122, 0.7911],
        [0.1845, 0.8457, 0.9593, 0.0202]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [190]:
# Lets make som random nu reproducble tenosrs
import torch

RANDOM_SEED=42
torch.manual_seed=RANDOM_SEED
random_tensor_C=torchrand(3,4)

troch.manual_seed(Ra)

In [191]:
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Extra resorce for reproducanility "Random seed wiki"

In [192]:
 ##RUnning tensor and Pytorchobjects on the GPUS (and making faster computations)
 #GPUs= faster computation on numbers , thanks to cuda +NVDIA hardware + Pytorch working behinf  verything hunky dory(good)

### 1. Getting a GPU
#1. Easiest -Use Google COlab for a free GPU (option to upgrade as well)
# 2. Use own GPU
# use cloaud computing GCP, AWS, Azure :https://timdettmers.com/2023/01/30/which-gpu-for-deep-learning/


In [1]:
!nvidia-smi

Tue Aug 12 22:46:23 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A100-SXM4-40GB          Off |   00000000:00:04.0 Off |                    0 |
| N/A   31C    P0             43W /  400W |       0MiB /  40960MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+-----

In [12]:
##check for GPU acess with PyTorch
import torch
torch.cuda.is_available()

True

In [14]:
#Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [15]:
torch.cuda.device_count()

1

In [5]:
#Create a tensor (default on the CPU)
tensor=torch.tensor([1,2,3])

#Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [9]:
#Move tensor to gpu
tensor_on_gpu=tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [7]:
#if tensir is on gp cant transform to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [10]:
tensor_back_on_cpu=tensor_on_gpu.cpu().numpy()